---

pr:
- master

trigger:
- '*'

# use self-hosted agent
pool:
  name: Default
  demands:
  - agent.name -equals Agent1

stages:
- template: azure-pipelines/pr-validation-build.yml
- template: azure-pipelines/build.yml
# - template: azure-pipelines/production.yml

...
